domain_sz: [20,20,20]
particle_radius: 0.25
dt: 0.05
materials:
    -
        is_liquid: 1
        density: 1
        color: [0.26666667, 1.        , 0.82352941]
    -
        is_liquid: 1
        density: 10
        color: [0.82352941, 1.        , 0.26666667]
objects:
    -
        material: 0
        shape: cube
        size: [10, 10, 10]
        center: [5, 10, 5]
    -
        material: 1
        shape: cube
        size: [10, 10, 10]
        center: [15, 10, 15]
        
solver:
    type: PBD

