domain_sz: [20,20,20]
particle_radius: 0.25
dt: 0.05
materials:
    -
        is_liquid: 1
        density: 1
        color: [0.26666667, 1.        , 0.82352941]
    -
        is_liquid: 0
        density: 0.4
        color: [0.82352941, 1.        , 0.26666667]
objects:
    -
        material: 0
        shape: cube
        size: [15, 10, 15]
        center: [7.5, 5, 7.5]
    -
        material: 1
        shape: cube
        size: [5, 5, 5]
        center: [10, 13, 10]
        thickness: 2

solver:
    type: PBD
    stabilization_iteration: 50
