domain_sz: [20,20,20]
particle_radius: 0.25
dt: 0.05
materials:
    -
        is_liquid: 1
        density: 1
        color: [0.26666667, 1.        , 0.82352941]
objects:
    -
        material: 0
        shape: cube
        size: [15, 10, 15]
        center: [7.5, 5, 7.5]
solver:
    type: PBD
