domain_sz: [20,20,20]
particle_radius: 0.2
dt: 0.02
materials:
    -
        is_liquid: 0
        density: 1
        color: [0.26666667, 1.        , 0.82352941]
    -
        is_liquid: 0
        density: 1
        color: [0.82352941, 1.        , 0.26666667]
objects:
    -
        material: 0
        shape: cube 
        size: [5, 5, 5]
        center: [5, 10, 5]
        thickness: 1
    -
        material: 1
        shape: sphere
        radius: 2.5
        center: [10, 13, 10]
        thickness: 1
solver:
    type: PBD
    stabilization_iteration: 30

