domain_sz: [20,20,20]
particle_radius: 0.25
dt: 0.05
materials:
    -
        is_liquid: 1
        density: 2
        color: [0.26666667, 1.        , 0.82352941]
    -
        is_liquid: 1
        density: 1
        color: [1.        , 0.52941176, 0.66666667]
    
    -
        is_liquid: 0
        density: 0.4
        color: [0.82352941, 1.        , 0.26666667]
    -
        is_liquid: 0
        density: 1.2
        color: [0.14117647, 0.48235294, 0.62745098]
objects:
    -
        material: 0
        shape: cube
        start: [0, 0, 0]
        size: [10, 10, 10]
    -
        material: 1
        shape: cube
        start: [10, 0, 10]
        size: [10, 10, 10]

    -
        material: 2
        shape: sphere
        radius: 3
        center: [16, 17, 4]
        thickness: 1
    -
        material: 3
        shape: cube
        size: [5, 5, 5]
        center: [4, 15, 10]
        thickness: 1
solver:
    stabilization_iteration: 50
