dims: 3
domain_sz: [20,20,20] # optional
particle_radius: 0.25 # optional, support radius will be 4 times this value
# padding: 0.4 # optional, default to support radius
dt: 0.05
materials:
    -
        is_liquid: 1
        density: 1
        color: [0.26666667, 1.        , 0.82352941]
    -
        is_liquid: 1
        density: 10
        color: [0.82352941, 1.        , 0.26666667]
objects:
    -
        material: 0
        shape: cube # should be either cube, ellip or the path to the obj file (not yet implemented)
        # cube parameters:
        # start: [3, 3, 3]
        size: [8, 10, 8]
        center: [5, 10, 5]
    -
        material: 1
        shape: cube # should be either cube, ellip or the path to the obj file (not yet implemented)
        # cube parameters:
        # start: [3, 3, 3]
        size: [8, 10, 8]
        center: [15, 10, 15]
        # obj parameters:
        # TODO: not yet implmented
        # shape: ellip
        # center: [0.5, 0.5, 0.5] # can use either center or start to define the location
        # # start: [0.0, 0.0, 0.0] # if both are specified, will use start
        # size: [0.3, 0.2, 0.5]
solver:
    type: PBF
    # PBF parameters
    # -S_CORR-
    S_Corr_delta_q: 0.3 # optional, actual value would be this value times support radius, should between 0 and 1, best in [0.1, 0.3]
    S_Corr_k: 0.0001 # optional, recommanded value as default
    S_Corr_n: 4 # optional, recommanded value as default

    lambda_epsilon: 100.0 # optional

    # -Confinement / XSPH Viscosity-
    xsph_c: 0.01 # optional
    vorti_epsilon: 0.01 # optional
    solver_iteration: 20 # optional

